import {test} from 'node:test';import assert from 'node:assert/strict';import {compareMessage,explicitProperties,type Property} from './comparison.ts';import type {Evaluate,EvaluationRequest,Evaluation} from './typesafe.ts';
const bank:Property[]=[{id:'density',aliases:['Density'],definition:'Mass per volume.'},{id:'hardness',aliases:['hardness'],definition:'Resistance to scratching.'}];
function response(request:EvaluationRequest,selected:Record<string,string>):Evaluation {return {model:'test',answers:Object.fromEntries(Object.entries(request.questions).map(([id,q])=>[id,{type:'choice',choice:selected[id],confidence:1,probabilities:Object.fromEntries(Object.keys(q.criteria).map(k=>[k,k===selected[id]?1:0]))}])),usage:{input_tokens:1,output_tokens:1}};}
test('explicit property detection does not match entity adjectives or generic words',()=>{assert.equal(explicitProperties('Compare A and B in density.',bank)[0].id,'density');assert.equal(explicitProperties('Compare the physical quantity for blue light.',bank).length,0);});
test('known comparisons use three evaluations on a small explicit bank and no EOS',async()=>{
 const seen:EvaluationRequest[]=[];const evaluate:Evaluate=async(r)=>{seen.push(r);if(r.questions.target){const find=(s:string)=>Object.entries(r.questions.target.criteria).find(([,v])=>v===s)![0];return response(r,{target:find('aluminum'),reference:find('lead')});}if(r.questions.property)return response(r,{property:'density'});return response(r,{direction:'lower',term:'t0'});};
 const result=await compareMessage('test',[{role:'user',content:'Compare aluminum and lead in density.'}],new AbortController().signal,()=>{},{evaluate,bank});
 assert.equal(result.text,'The density of aluminum is lower than that of lead.');assert.equal(result.requests,3);assert.equal(result.status,'complete');assert.equal(seen.length,3);
});
test('missing entities stop before catalog search or factual inference',async()=>{let calls=0;const evaluate:Evaluate=async(r)=>{calls++;return response(r,{target:'MISSING',reference:'MISSING'});};const result=await compareMessage('test',[{role:'user',content:'Compare density.'}],new AbortController().signal,()=>{},{evaluate,bank});assert.equal(result.status,'missing_entities');assert.equal(calls,1);});
test('unknown values are not turned into a directional claim',async()=>{const evaluate:Evaluate=async(r)=>{if(r.questions.target){const find=(s:string)=>Object.entries(r.questions.target.criteria).find(([,v])=>v===s)![0];return response(r,{target:find('sample A'),reference:find('sample B')});}if(r.questions.property)return response(r,{property:'density'});return response(r,{direction:'unknown',term:'t0'});};const result=await compareMessage('test',[{role:'user',content:'Compare sample A and sample B in density.'}],new AbortController().signal,()=>{},{evaluate,bank});assert.equal(result.status,'unknown');assert.equal(result.direction,'unknown');});
test('cancellation after an evaluation prevents the next one and no reply is emitted',async()=>{const controller=new AbortController();let calls=0;const evaluate:Evaluate=async(r)=>{calls++;controller.abort();return response(r,{target:'MISSING',reference:'MISSING'});};await assert.rejects(compareMessage('test',[{role:'user',content:'Compare two samples.'}],controller.signal,()=>{},{evaluate,bank}));assert.equal(calls,1);});
